authentication/urls.py
from django.urls import path
from .views import RegisterView, HomeView

app_name='auth'
urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),
    path('home', HomeView.as_view(), name='home'),
]

book/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views
from .views import logout_view

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include(('authentication.urls', 'authentication'), namespace='authentication')),
    
    path('', include(('bookstore.urls', 'bookstore'), namespace='bookstore')),
    
    path('profile', include(('profiles.urls', 'profiles'), namespace='profiless')),
    
    path('login/', views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', logout_view, name='logout'),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bookstore/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views


urlpatterns = [
    path('', views.MainView.as_view(), name='main'),
    path('genre/<slug:slug>', views.GenreView.as_view(), name='genres'),
    path('book/<slug:slug>', login_required(views.BookView.as_view()), name='books'),
    path('books', views.BookListView.as_view(), name='books_list'),
]

profiles/urls.py
from django.urls import path
from profiles.views import IndexView


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('', IndexView.as_view(), name='profile'),
]

authentication/models.py
from django.db import models

# Create your models here.

bookstore/models.py
from django.db import models
from django.urls import reverse_lazy
from django.template.defaultfilters import slugify, truncatechars


class Book(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    label = models.ImageField(upload_to='books/%Y/%m/%d')
    author = models.ForeignKey('Author', null=True, blank=True, on_delete=models.SET_NULL)
    soft_deleted = models.BooleanField(default=False)
    genre = models.ManyToManyField('Genre', blank=True)
    viewers = models.IntegerField(default=1, editable=False)
    likes = models.IntegerField(default=0, editable=False)
    file = models.FileField(upload_to='books/files/%Y/%m/%d', null=True, blank=True, help_text='Файл(книга)')
    slug = models.SlugField(max_length=255, null=True, blank=True, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    
    def __str__(self):
        return f'{self.title}'
    
    @property
    def short_description(self):
        return truncatechars(self.description, 35)
    
    @property
    def get_description(self):
        return truncatechars(self.description, 400)
    
    def get_absolute_url(self):
        return reverse_lazy('bookstore:books', kwargs={'slug': self.slug})
        
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)
        
    def addViewers(self, *args, **kwargs):
        self.viewers += 1
        super().save(*args, **kwargs)
    
    class Meta:
        verbose_name = 'Книги'
        verbose_name_plural = 'Книги'
        ordering = ('-created',)
        

class Author(models.Model):
    name = models.CharField(max_length=255)
    fullname = models.CharField(max_length=255, help_text='Полная И.Ф.О')
    soft_deleted = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} ({self.fullname})'
    
    class Meta:
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'
    

class Genre(models.Model):
    title = models.CharField(max_length=255, verbose_name='Жанр')
    slug = models.SlugField(max_length=255, null=True, blank=True, editable=False)
    status = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title}'
    
    def get_absolute_url(self):
        return reverse_lazy('bookstore:genres', kwargs={'slug': self.slug})
        
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    
    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile', blank=True, null=True)
    phone = models.CharField(max_length=12, verbose_name='Phone number', blank=True, null=True)
    address = models.CharField(verbose_name='Address', max_length=255, blank=True, null=True)

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


post_save.connect(create_user_profile, sender=User)

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

authentication/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User 
from django.http import HttpResponseRedirect
from .forms import RegisterForm


class HomeView(LoginRequiredMixin, TemplateView):
    login_url = '/accounts/login'
    template_name = 'home/home.html'


class RegisterView(TemplateView):
    template_name = 'account/register.html'
    
    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/accounts/login')
        else:
            return render(request, 'account/register.html')

book/views.py
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView
from django.http import HttpResponse
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login


class MainView(TemplateView):
    template_name='home/main.html'
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)


def logout_view(request):
    logout(request)
    return redirect('/accounts/login')

bookstore/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from .models import Book, Genre
from django.http import Http404
from django.utils import timezone


class MainView(TemplateView):
    template_name='home/main.html'
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['genres'] = Genre.objects.all()[:6]
        
        return context


class GenreView(TemplateView):
    template_name='book/books.html'
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['genre'] = Genre.objects.get(slug=kwargs.get('slug', None), status=True)
        context['books'] = context['genre'].book_set.all()
        
        return context


class BookView(DetailView):
    model = Book
    template_name='book/details.html'
    
    def get_object(self, queryset=None):
        slug = self.kwargs.get(self.slug_url_kwarg, None)
        try:
            book = Book.objects.get(slug=slug)
            book.addViewers()
            return book
        except Exception:
            raise Http404('Ох, нет объекта;)')
    

class BookListView(ListView):
    model = Book
    paginate_by = 10
    template_name = 'book/books.html'
    context_object_name = 'books'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

profiles/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'home/main.html'

templates/book/books.html
{% extends "layout/guest_app.html" %}
{% load static %}

{% block title %}Книги{% endblock %}    

{% block content %}
    <section class="admin-content">
        <div class="bg-dark m-b-30">
            <div class="container">
                <div class="row p-b-60 p-t-60">

                    <div class="col-md-12 m-auto text-white">

                        <h1> {{ genre }}</h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb bg-transparent">
                                <li class="breadcrumb-item"><a>Жанр</a></li>
                                <li class="breadcrumb-item active" ><a>Книги</a></li>
                                {% if user.is_authenticated %}
                                    <a href="{% url 'authentication:home' %}"
                                        style="margin-left: 90%;
                                        float: right;
                                        position: absolute;"
                                    >
                                    <i class="mdi mdi-keyboard-backspace"></i>
                                    Главная</a>
                                {% else %}
                                    <a href="{% url 'bookstore:main' %}"
                                        style="margin-left: 90%;
                                        float: right;
                                        position: absolute;"
                                    >
                                    <i class="mdi mdi-keyboard-backspace"></i>
                                    Назад</a>
                                {% endif %}
                            </ol>
                        </nav>

                    </div>

                </div>
            </div>
        </div>
        <div class="container pull-up">
            <div class="row">
                {% for book in books %}
                <div class="col-md-12 m-b-30">
                    <div class="card mb-4">
                        <div class="card-header">
                            <div class="media flex-wrap align-items-center">
                                <div class="avatar avatar">
                                    <img src="{{ book.label.url }}" alt="..."
                                        class="avatar-img rounded-circle">
                                </div>
                                <div class="media-body ml-3">
                                    <a href="#!">{{ book.author.name }}</a>
                                    <div class="text-muted small">{{ book.created }}</div>
                                </div>
                                <div class="text-muted small ml-3">
                                    <div>Member since <strong>{{ book.created | date:"Y/m/d" }}</strong></div>
                                    <div><strong>{{ book.viewers }}</strong> views</div>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <p>
                                {{ book.get_description }}
                            </p>
                        </div>
                        <div class="card-footer d-flex flex-wrap justify-content-between align-items-center px-0 pt-0 pb-3">
                            <div class="px-4 pt-3">
                                <a href="#!" class="text-muted">
                                    <i class="mdi mdi-heart text-danger text-large align-middle"></i>&nbsp;
                                    <span class="align-middle">{{ book.likes }}</span>
                                </a>
                                <span class="text-muted ml-4">
                                    <i class="mdi mdi-eye-outline  text-large align-middle"></i>&nbsp;
                                    <span class="align-middle">{{ book.viewers }}</span>
                                </span>
                            </div>
                            <div class="px-4 pt-3">
                                <a href="{{ book.get_absolute_url }}" class="btn btn-primary"><i class="mdi mdi-arrow-right"></i> Читать</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

templates/book/details.html
{% extends "layout/guest_app.html" %}
{% load static %}

{% block title %}Книги{% endblock %}    

{% block content %}
    <section class="admin-content">
        <div class="bg-dark m-b-30">
            <div class="container">
                <div class="row p-b-60 p-t-60">

                    <div class="col-md-12 m-auto text-white">

                        <h1> {{ genre }}</h1>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb bg-transparent">
                                <li class="breadcrumb-item"><a> Книги</a></li>
                                <li class="breadcrumb-item active" ><a>{{ book.title }}</a></li>
                            </ol>
                        </nav>

                    </div>

                </div>
            </div>
        </div>
        <div class="container pull-up">
            <div class="row">
                <div class="col-md-12 m-b-30">
                    <div class="card mb-4">
                        <div class="card-header">
                            <div class="media flex-wrap align-items-center">
                                <div class="avatar avatar">
                                    <img src="{{ book.label.url }}" alt="..."
                                        class="avatar-img rounded-circle">
                                </div>
                                <div class="media-body ml-3">
                                    <a href="#!">{{ book.author.name }}</a>
                                    <div class="text-muted small">{{ book.created }}</div>
                                </div>
                                <div class="text-muted small ml-3">
                                    <div>Member since <strong>{{ book.created | date:"Y/m/d" }}</strong></div>
                                    <div><strong>{{ book.viewers }}</strong> views</div>
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <p>
                                {{ book.description }}
                            </p>
                        </div>
                        <div class="card-footer d-flex flex-wrap justify-content-between align-items-center px-0 pt-0 pb-3">
                            <div class="px-4 pt-3">
                                <a href="#!" class="text-muted">
                                    <i class="mdi mdi-heart text-danger text-large align-middle"></i>&nbsp;
                                    <span class="align-middle">{{ book.likes }}</span>
                                </a>
                                <span class="text-muted ml-4">
                                    <i class="mdi mdi-eye-outline  text-large align-middle"></i>&nbsp;
                                    <span class="align-middle">{{ book.viewers }}</span>
                                </span>
                            </div>
                            <div class="px-4 pt-3">
                                <a href="{{ book.file.url }}" class="btn btn-success" target="_blank">
                                    <i class="mdi mdi-cloud-download-outline"></i> Скачать
                                </a>
                                <a href="{% url 'auth:home' %}"  class="btn btn-primary">
                                    <i class="mdi mdi-keyboard-backspace"></i>Назад
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/home/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" name="viewport">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <title>Книжный интернет-магазин</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/img/logo.png' %}"/>
    <link rel="icon" href="{% static 'assets/img/logo.png' %}" type="image/png" sizes="16x16">
    <link rel="stylesheet" href="{% static 'assets/vendor/pace/pace.css' %}">
    <script src="{% static 'assets/vendor/pace/pace.min.js' %}"></script>
    <!--vendors-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/jquery-scrollbar/jquery.scrollbar.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendor/select2/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendor/jquery-ui/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendor/daterangepicker/daterangepicker.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendor/timepicker/bootstrap-timepicker.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Hind+Vadodara:400,500,600" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/fonts/jost/jost.css' %}">
    <!--Material Icons-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/fonts/materialdesignicons/materialdesignicons.min.css' %}">
    <!--Bootstrap + atmos Admin CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/atmos.min.css' %}">
    <!-- Additional library for page -->

</head>
<body class="sidebar-pinned">   
<section class="admin-content">
        <div class=" bg-dark m-b-30 ">
            <div class="container">
                <div class="row">
                    <div class="col-8 m-auto text-white p-t-40 p-b-90">

                        <h1 class="fw-300 text-center">Книжный магазин
                        </h1>
                        <p class="p-t-30 form-dark">
                            <input name="search" type="search" placeholder="Поиск по названию, автору" class=" form-control form-control-lg">
                        </p>

                    </div>
                </div>
            </div>

        </div>
        <div class="container pull-up">
            <div class="row m-b-90">
                {% for genre in genres %}
                    <div class="col-lg-4 col-md-6">
                        <a href="{{ genre.get_absolute_url }}" class="card shadow-lg guide-item m-b-30  bg-primary">
                            <div class="card-body text-white" 
                            style="background-image: url('/static/assets/img/photos/photo9.jpg');
                                background-repeat: no-repeat;
                                background-size: 100% 100%;">
                                <h4 class=" p-t-20 ">{{ genre }}</h4>
                                <p>Смотреть всех</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>

    </section>

</main>

<script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'assets/vendor/jquery-ui/jquery-ui.min.js' %}"></script>
<script src="{% static 'assets/vendor/popper/popper.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/vendor/select2/js/select2.full.min.js' %}"></script>
<script src="{% static 'assets/vendor/jquery-scrollbar/jquery.scrollbar.min.js' %}"></script>
<script src="{% static 'assets/vendor/listjs/listjs.min.js' %}"></script>
<script src="{% static 'assets/vendor/moment/moment.min.js' %}"></script>
<script src="{% static 'assets/vendor/daterangepicker/daterangepicker.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'assets/vendor/bootstrap-notify/bootstrap-notify.min.js' %}"></script>
<script src="{% static 'assets/js/atmos.min.js' %}"></script>
<!--page specific scripts for demo-->

</body>
</html>

templates/layout/admin.sidebar.html
{% load static %}
<aside class="admin-sidebar">
    <div class="admin-sidebar-brand">
        <!-- begin sidebar branding-->
        <img class="admin-brand-logo" src="{% static 'assets/img/logo.png' %}" width="40" alt="atmos Logo">
        <span class="admin-brand-content font-secondary"><a href="{% url 'auth:home' %}">  BookStore</a></span>
        <!-- end sidebar branding-->
        <div class="ml-auto">
            <!-- sidebar pin-->
            <a href="#" class="admin-pin-sidebar btn-ghost btn btn-rounded-circle"></a>
            <!-- sidebar close for mobile device-->
            <a href="#" class="admin-close-sidebar"></a>
        </div>
    </div>
    <div class="admin-sidebar-wrapper js-scrollbar">
        <ul class="menu">
            <li class="menu-item active ">
                <a href="{% url 'auth:home' %}" class=" menu-link">
                        <span class="menu-label">
                            <span class="menu-name">
                                Dashboard
                            </span>
                        </span>
                    <span class="menu-icon">
                            <i class="icon-placeholder mdi mdi-shape-outline "></i>
                    </span>
                </a>
            </li>
            <li class="menu-item active ">
                <a href="{% url 'bookstore:books_list' %}" class=" menu-link">
                    <span class="menu-label">
                        <span class="menu-name">
                            Books
                        </span>
                    </span>
                    <span class="menu-icon">
                        <i class="icon-placeholder mdi mdi-library-books "></i>
                    </span>
                </a>
            </li>
            <li class="menu-item">
                <a href="#" class="open-dropdown menu-link">
                        <span class="menu-label">
                            <span class="menu-name">History
                                <span class="menu-arrow"></span>
                            </span>
                        </span>
                    <span class="menu-icon">
                        <i class="icon-placeholder mdi mdi-chat "></i>
                    </span>
                </a>
                <!--submenu-->
                <ul class="sub-menu">
                    <li class="menu-item">
                        <a href="forum-home.html" class=" menu-link">
                            <span class="menu-label">
                                <span class="menu-name">Likes </span>
                            </span>
                            <span class="menu-icon">
                                <i class="icon-placeholder  ">
                                    <i class="icon mdi mdi-heart"></i>
                                </i>
                            </span>
                        </a>
                        <a href="forum-home.html" class=" menu-link">
                            <span class="menu-label">
                                <span class="menu-name">Downloads </span>
                            </span>
                            <span class="menu-icon">
                                <i class="icon-placeholder  ">
                                    <i class="icon mdi mdi-cloud-download"></i>
                                </i>
                            </span>
                        </a>
                    </li>

                </ul>
            </li>
        </ul>

    </div>

</aside>

templates/layout/guest_app.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" name="viewport">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <title>{% block title %}Lenger{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="assets/img/logo.png' %}"/>
    <link rel="icon" href="{% static 'assets/img/logo.png' %}" type="image/png" sizes="16x16">
    <link rel="stylesheet" href="{% static 'assets/vendor/pace/pace.css' %}">
    <script src="{% static 'assets/vendor/pace/pace.min.js' %}"></script>
    <!--vendors-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/vendor/jquery-scrollbar/jquery.scrollbar.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendor/select2/css/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendor/jquery-ui/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendor/daterangepicker/daterangepicker.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendor/timepicker/bootstrap-timepicker.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Hind+Vadodara:400,500,600" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/fonts/jost/jost.css' %}">
    <!--Material Icons-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/fonts/materialdesignicons/materialdesignicons.min.css' %}">
    <!--Bootstrap + atmos Admin CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/atmos.min.css' %}">
    <!-- Additional library for page -->

    {% block style %}{% endblock %}

</head>
<body class="sidebar-pinned">

        <!--site header ends -->
        <section class="admin-content ">
            <div class="container py-5">
                {% block content %}{% endblock %}
            </div>
        </section>
    </main>

    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/jquery-ui/jquery-ui.min.js' %}"></script>
    <script src="{% static 'assets/vendor/popper/popper.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/vendor/select2/js/select2.full.min.js' %}"></script>
    <script src="{% static 'assets/vendor/jquery-scrollbar/jquery.scrollbar.min.js' %}"></script>
    <script src="{% static 'assets/vendor/listjs/listjs.min.js' %}"></script>
    <script src="{% static 'assets/vendor/moment/moment.min.js' %}"></script>
    <script src="{% static 'assets/vendor/daterangepicker/daterangepicker.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap-notify/bootstrap-notify.min.js' %}"></script>
    <script src="{% static 'assets/js/atmos.min.js' %}"></script>
    <!--page specific scripts for demo-->

    <!--Additional Page includes-->
    <script src="{% static 'assets/vendor/apexchart/apexcharts.min.js' %}"></script>
    <!--chart data for current dashboard-->
    <script src="{% static 'assets/js/dashboard-01.js' %}" type="text/javascript"></script>

    {% block scripts %}
    {% endblock %}
</body>
</html>